version: '3.5'

services:
    app-ponto:
        container_name: app-ponto
        hostname: app-ponto.localhost
        restart: always
        build:
            context: ./docker/build/php-fpm
            dockerfile: Dockerfile
        working_dir: /var/www/html/app-ponto
        expose:
            - "9000"
        environment:
            - COMPOSER_MEMORY_LIMIT=-1
           #- PHP_IDE_CONFIG:serverName=Xdebug
        volumes:
            - ./:/var/www/html/app-ponto
            - ./docker/build/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - MyNetwork

networks:
    MyNetwork:
        driver: bridge
        name: MyNetwork
